from application.models.assistance import Assistance
from application.models.cirgury import Cirgury
from application.models.customer_detail import CustomerDetail
from application.models.client import Client
from application.models.emergency_contact import EmergencyContact
from application.models.payment_methods import PaymentMethod
from application.models.payment import Payment
from application.models.profession import Profession
from application.models.sickness import Sickness
from application.models.user import User